global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
        labels:
          source: 'localhost'
          metricsrc: 'nodeexporter'
      - targets: ['95.217.36.182:33903']
        labels:
          source: 'elrond-bon-vm'
          metricsrc: 'easy2stake-exporter'
      - targets: ['95.217.36.182:33905']
        labels:
          source: 'elrond-mainnet1'
          metricsrc: 'easy2stake-exporter'
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
